README.md: Change `release` to `released`
coala/coAST pull request #104
Opened 2019-01-17 19:42 UTC by asrdav

Fixes #76 

For short term contributors: we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Checklist
  I read the commit guidelines and I've followed
them.
  I ran coala over my code locally. (All commits have to pass
individually. It is not sufficient to have "fixup commits" on your PR,
our bot will still report the issues for the previous commit.) You will
likely receive a lot of bot comments and build failures if coala does not
pass on every single commit!
After you submit your pull request, DO NOT click the 'Update Branch' button.
When asked for a rebase, consult coala.io/rebase
instead.

Please consider helping us by reviewing other peoples pull requests as well:

pick up any PR at https://coala.io/review
review it (check https://coala.io/reviewing for more info)
if you are sure that it needs work, use corobo mark wip <URL> to get it out
of the review queue.
The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

2019-01-18 17:18 UTC, siddhpant commented
Close this duplicate.

2019-01-18 17:20 UTC, asrdav commented
I can't understand you

2019-01-18 17:21 UTC, asrdav commented
I was not able to get the commit message errors. So, I read the commit guidelines and then I made the rest pull requests. But they also failed.

2019-01-18 17:25 UTC, asrdav commented
I closed all the other duplicate PR's.

2019-01-20 05:00 UTC, shashank-b requested changes
Please don't close this PR, 3 others have already been closed.
Also, squash the commits and follow the commit guidelines for the final commit.

2019-01-20 05:38 UTC, asrdav commented
I read the commit guidelines but I am getting errors. I might be doing something wrong. Can you please help me with what is wrong in the heading of the PR.

2019-01-20 05:44 UTC, shashank-b commented
But you aren't following the commit guidelines. Squash the commits and change the message. Meanwhile, I'll check what the errors are.

2019-01-20 05:46 UTC, shashank-b commented
The netlify errors are not because of your change. Don't worry about them. Just do this -
>Also, squash the commits and follow the commit guidelines for the final commit.

2019-01-20 05:59 UTC, asrdav commented
Will do

2019-01-31 06:50 UTC, jayvdb commented
Ping. Please fix.

2019-01-31 06:58 UTC, asrdav commented
Don't worry, I will fix this issue by this Sunday.
On Jan 31, 2019 12:20, "John Vandenberg" <notifications@github.com> wrote:

> Ping. Please fix.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coala/coAST/pull/104#issuecomment-459235793>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AcUIb_tHkRs90SrrzP2HjUyDrZfNzv3hks5vIpIbgaJpZM4aGmvM>
> .
>

2019-02-03 19:49 UTC, closed without merging